spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

# App Properties
appConfig:
  app:
    jwtSecret: bgPersonnelSecretKey
    jwtExpirationMs: 6000000
    jwtRefreshExpirationMs: 12000000
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080