version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/db_budget_personnel_dev
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=password
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=mailhog
      - MAIL_PASSWORD=mailhog
    depends_on:
      - db
      - mailhog
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=db_budget_personnel_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
        - "5432:5432"
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"