name: Java

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      #Set up Maven cache
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      #Run Tests
      - name: Run Tests
        run: mvn -B test
        env:
          DATASOURCE_PASSWORD: ''
          DATASOURCE_URL: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          DATASOURCE_USERNAME: sa
          MAIL_HOST: 0.0.0.0
          MAIL_PASSWORD: mailhog
          MAIL_PORT: 1025
          MAIL_USERNAME: mailhog
          SPRING_PROFILES_ACTIVE: test

      #Analyze project with SonarCloud
      - name: Analyze with SonarCloud
        run: mvn -B -X verify sonar:sonar -Dsonar.projectKey=sahraoui9_budget-personnel -Dsonar.organization=pg-p -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DATASOURCE_PASSWORD: ''
          DATASOURCE_URL: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          DATASOURCE_USERNAME: sa
          MAIL_HOST: 0.0.0.0
          MAIL_PASSWORD: mailhog
          MAIL_PORT: 1025
          MAIL_USERNAME: mailhog
          SPRING_PROFILES_ACTIVE: test